export function createStyles(theme) {
  return {
    appBg: {
      minHeight: "100vh",
      padding: "24px 16px 120px",
      fontFamily:
        'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      transition: "background 180ms ease, color 180ms ease",
    },
    container: {
      maxWidth: 1120,
      margin: "0 auto",
    },
    pageContent: {
      display: "grid",
      gap: 20,
    },
    pageHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 16,
      flexWrap: "wrap",
    },
    eyebrow: {
      fontSize: 13,
      fontWeight: 800,
      textTransform: "uppercase",
      letterSpacing: ".08em",
      marginBottom: 6,
    },
    pageTitle: {
      margin: 0,
      fontSize: "clamp(2rem, 3vw, 3.25rem)",
      lineHeight: 1.05,
    },
    pageDescription: {
      margin: "8px 0 0",
      fontSize: 16,
      lineHeight: 1.6,
    },
    card: {
      border: "1px solid",
      borderRadius: 28,
      padding: 22,
      backdropFilter: "blur(10px)",
      transition: "all 180ms ease",
    },
    heroCard: {
      color: "#fff",
      borderRadius: 32,
      padding: 28,
      display: "flex",
      justifyContent: "space-between",
      gap: 20,
      flexWrap: "wrap",
      boxShadow: theme.shadow,
    },
    heroArabic: {
      fontSize: "clamp(2rem, 4vw, 3rem)",
      fontWeight: 800,
    },
    heroText: {
      margin: "8px 0 0",
      fontSize: 18,
      opacity: 0.92,
    },
    heroStats: {
      minWidth: 120,
      borderRadius: 24,
      background: "rgba(255,255,255,0.14)",
      padding: 20,
      display: "grid",
      placeItems: "center",
      textAlign: "center",
      gap: 6,
      border: "1px solid rgba(255,255,255,0.18)",
    },
    heroStatsNumber: {
      fontSize: 34,
      color: "#fde68a",
    },
    sectionTag: {
      fontWeight: 800,
      textTransform: "uppercase",
      fontSize: 12,
      letterSpacing: ".08em",
    },
    ayahArabic: {
      marginTop: 16,
      fontSize: "clamp(2rem, 3vw, 2.6rem)",
      lineHeight: 1.8,
      textAlign: "right",
    },
    ayahTranslation: {
      margin: "12px 0 0",
      fontSize: 18,
      lineHeight: 1.7,
    },
    ayahRef: {
      marginTop: 12,
      fontWeight: 700,
    },
    sectionHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    sectionTitle: {
      margin: 0,
      fontSize: 24,
      lineHeight: 1.2,
    },
    sectionMeta: {
      fontSize: 14,
    },
    quickGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
      gap: 16,
    },
    quickAction: {
      border: "1px solid",
      borderRadius: 24,
      padding: 20,
      display: "grid",
      gap: 10,
      textAlign: "left",
      cursor: "pointer",
      boxShadow: "0 10px 24px rgba(15,23,42,0.04)",
    },
    quickActionPrimary: {
      color: "#fff",
      border: "none",
    },
    quickActionEmoji: {
      fontSize: 24,
    },
    gridList: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
      gap: 16,
    },
    recommendationCard: {
      border: "1px solid",
      borderRadius: 24,
      padding: 18,
      display: "grid",
      gap: 10,
      textAlign: "left",
      cursor: "pointer",
      boxShadow: "0 10px 24px rgba(15,23,42,0.04)",
    },
    recommendationTop: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    recommendationIndex: {
      width: 38,
      height: 38,
      borderRadius: 12,
      display: "grid",
      placeItems: "center",
      fontWeight: 800,
    },
    recommendationTitle: {
      fontSize: 20,
    },
    recommendationText: {},
    recommendationArabic: {
      fontSize: 28,
    },
    playerHero: {
      display: "grid",
      gap: 16,
    },
    playerHeroLabel: {
      fontWeight: 800,
      fontSize: 13,
      textTransform: "uppercase",
      letterSpacing: ".08em",
    },
    playerHeroTitle: {
      fontSize: 30,
      fontWeight: 800,
      marginTop: 8,
    },
    playerHeroMeta: {
      marginTop: 6,
      fontSize: 16,
    },
    playerActionsWrap: {
      display: "flex",
      flexWrap: "wrap",
      gap: 12,
    },
    loopBanner: {
      border: "1px solid",
      borderRadius: 18,
      padding: "12px 14px",
      fontWeight: 700,
    },
    reciterGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
      gap: 16,
    },
    reciterCard: {
      display: "grid",
      gap: 16,
    },
    reciterCardTop: {
      display: "flex",
      gap: 16,
      alignItems: "center",
    },
    reciterImage: {
      width: 84,
      height: 84,
      borderRadius: 22,
      objectFit: "cover",
      background: "#f3f4f6",
      flexShrink: 0,
    },
    reciterCardInfo: {
      minWidth: 0,
    },
    reciterName: {
      margin: 0,
      fontSize: 20,
    },
    reciterDescription: {
      margin: "6px 0 0",
      lineHeight: 1.6,
    },
    reciterActions: {
      display: "flex",
      gap: 10,
      flexWrap: "wrap",
    },
    readingToolbarGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
      gap: 14,
    },
    fieldWrap: {
      display: "grid",
      gap: 8,
    },
    label: {
      fontSize: 14,
      fontWeight: 700,
    },
    input: {
      height: 50,
      borderRadius: 16,
      border: "1px solid",
      padding: "0 14px",
      fontSize: 16,
      outline: "none",
    },
    select: {
      height: 50,
      borderRadius: 16,
      border: "1px solid",
      padding: "0 14px",
      fontSize: 16,
      outline: "none",
    },
    readingActions: {
      display: "flex",
      flexWrap: "wrap",
      gap: 12,
      marginTop: 16,
    },
    helperText: {
      marginTop: 12,
      fontSize: 14,
      lineHeight: 1.6,
    },
    stack: {
      display: "grid",
      gap: 14,
    },
    surahCard: {
      display: "flex",
      alignItems: "stretch",
      gap: 12,
      border: "1px solid",
      borderRadius: 24,
      padding: 14,
      transition: "all 160ms ease",
    },
    surahCardMain: {
      flex: 1,
      border: "none",
      background: "transparent",
      display: "flex",
      alignItems: "center",
      gap: 16,
      cursor: "pointer",
      textAlign: "left",
      minWidth: 0,
    },
    surahIndex: {
      width: 48,
      height: 48,
      borderRadius: 16,
      display: "grid",
      placeItems: "center",
      fontWeight: 800,
      flexShrink: 0,
    },
    surahInfo: {
      flex: 1,
      minWidth: 0,
    },
    surahTitle: {
      fontSize: 20,
      fontWeight: 800,
    },
    surahMeta: {
      display: "flex",
      gap: 8,
      alignItems: "center",
      flexWrap: "wrap",
      marginTop: 6,
    },
    surahArabic: {
      fontSize: 28,
      whiteSpace: "nowrap",
    },
    bookmarkButton: {
      width: 48,
      border: "1px solid",
      borderRadius: 16,
      cursor: "pointer",
      fontSize: 20,
      flexShrink: 0,
    },
    badge: {
      padding: "6px 10px",
      borderRadius: 999,
      fontWeight: 700,
      fontSize: 12,
    },
    statusLight: {
      width: 10,
      height: 10,
      borderRadius: 999,
      display: "inline-block",
      transition: "all 160ms ease",
    },
    surahSummaryTop: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 16,
      flexWrap: "wrap",
    },
    currentSurahTitleWrap: {
      display: "flex",
      alignItems: "center",
      gap: 10,
    },
    currentSurahArabic: {
      fontSize: 34,
    },
    verseCard: {
      width: "100%",
      border: "1px solid",
      borderRadius: 26,
      padding: 18,
      textAlign: "left",
      cursor: "pointer",
      transition: "all 160ms ease",
    },
    verseTopRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      flexWrap: "wrap",
    },
    verseTopLeft: {
      display: "flex",
      alignItems: "center",
      gap: 10,
    },
    verseTopActions: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      flexWrap: "wrap",
    },
    verseBadge: {
      width: 38,
      height: 38,
      borderRadius: 999,
      display: "grid",
      placeItems: "center",
      fontWeight: 800,
    },
    liveBadge: {
      padding: "6px 10px",
      borderRadius: 999,
      fontWeight: 800,
      fontSize: 12,
    },
    loopChip: {
      border: "1px solid",
      borderRadius: 999,
      padding: "8px 12px",
      fontWeight: 700,
      cursor: "pointer",
    },
    verseArabic: {
      marginTop: 16,
      fontSize: "clamp(2rem, 3vw, 2.4rem)",
      lineHeight: 1.9,
      textAlign: "right",
    },
    verseTransliteration: {
      marginTop: 12,
      lineHeight: 1.7,
      fontStyle: "italic",
      fontSize: 15,
    },
    verseTranslation: {
      marginTop: 12,
      lineHeight: 1.8,
      fontSize: 16,
    },
    loadingBox: {
      fontSize: 16,
    },
    errorBox: {
      color: "#7f1d1d",
    },
    errorText: {
      margin: "8px 0 0",
      lineHeight: 1.6,
    },
    planHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 16,
      flexWrap: "wrap",
    },
    planActions: {
      display: "flex",
      gap: 10,
      flexWrap: "wrap",
      marginTop: 16,
    },
    planChip: {
      border: "1px solid",
      borderRadius: 999,
      padding: "10px 14px",
      cursor: "pointer",
      fontWeight: 700,
    },
    emptyCard: {
      textAlign: "center",
      minHeight: 260,
      display: "grid",
      placeItems: "center",
      gap: 8,
    },
    emptyEmoji: {
      fontSize: 56,
    },
    themeGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
      gap: 14,
    },
    themeCard: {
      border: "1px solid",
      borderRadius: 22,
      padding: 14,
      textAlign: "left",
      cursor: "pointer",
      display: "grid",
      gap: 10,
    },
    themePreview: {
      height: 70,
      borderRadius: 16,
    },
    settingsGroup: {
      marginTop: 18,
      display: "grid",
      gap: 10,
    },
    settingsRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      flexWrap: "wrap",
    },
    settingsValue: {
      fontWeight: 800,
    },
    rangeInput: {
      width: "100%",
    },
    settingsSwitchList: {
      display: "grid",
      gap: 12,
      marginTop: 20,
    },
    toggleRow: {
      border: "1px solid",
      borderRadius: 20,
      padding: 16,
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 16,
      cursor: "pointer",
      textAlign: "left",
    },
    toggleHint: {
      marginTop: 6,
      fontSize: 14,
      lineHeight: 1.5,
    },
    togglePill: {
      width: 46,
      height: 28,
      borderRadius: 999,
      flexShrink: 0,
    },
    settingsActions: {
      marginTop: 18,
      display: "flex",
      flexWrap: "wrap",
      gap: 12,
    },
    bottomNavWrap: {
      position: "fixed",
      left: 16,
      right: 16,
      bottom: 16,
      zIndex: 40,
      display: "flex",
      justifyContent: "center",
      pointerEvents: "none",
    },
    bottomNav: {
      width: "min(100%, 960px)",
      border: "1px solid",
      borderRadius: 28,
      padding: 8,
      display: "grid",
      gridTemplateColumns: "repeat(6, 1fr)",
      gap: 8,
      boxShadow: "0 18px 45px rgba(15,23,42,0.12)",
      backdropFilter: "blur(12px)",
      pointerEvents: "auto",
    },
    bottomNavButton: {
      border: "none",
      background: "transparent",
      borderRadius: 20,
      padding: "12px 8px",
      display: "grid",
      justifyItems: "center",
      gap: 6,
      cursor: "pointer",
      fontWeight: 600,
      fontSize: 13,
    },
    bottomNavButtonActive: {},
    bottomNavIcon: {
      fontSize: 18,
    },
    miniPlayerWrap: {
      position: "fixed",
      left: 16,
      right: 16,
      bottom: 100,
      zIndex: 35,
      display: "flex",
      justifyContent: "center",
      pointerEvents: "none",
    },
    miniPlayer: {
      width: "min(100%, 960px)",
      border: "1px solid",
      borderRadius: 24,
      padding: 12,
      display: "flex",
      gap: 10,
      alignItems: "center",
      boxShadow: "0 16px 40px rgba(15,23,42,0.10)",
      backdropFilter: "blur(12px)",
      pointerEvents: "auto",
    },
    miniPlayerMain: {
      flex: 1,
      border: "none",
      background: "transparent",
      cursor: "pointer",
      textAlign: "left",
      minWidth: 0,
    },
    miniPlayerEyebrow: {
      fontSize: 12,
      fontWeight: 800,
      textTransform: "uppercase",
      letterSpacing: ".08em",
    },
    miniPlayerTitle: {
      marginTop: 4,
      fontWeight: 800,
      fontSize: 16,
    },
    miniPlayerMeta: {
      marginTop: 2,
      fontSize: 13,
    },
    primaryButton: {
      border: "none",
      color: "#fff",
      borderRadius: 16,
      padding: "12px 18px",
      fontWeight: 800,
      cursor: "pointer",
    },
    secondaryButton: {
      border: "1px solid",
      borderRadius: 16,
      padding: "12px 18px",
      fontWeight: 700,
      cursor: "pointer",
    },
    iconButtonDark: {
      width: 46,
      height: 46,
      border: "none",
      color: "#fff",
      borderRadius: 14,
      cursor: "pointer",
      fontSize: 16,
    },
    buttonDisabled: {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  };
}

